### ISSUE TITLE
Remove Java code failure semantics

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-ogcapi-features-1.0#76]
![image](https://user-images.githubusercontent.com/3738898/67052698-ef684380-f10c-11e9-878f-c07d2e87a978.png)

![image](https://user-images.githubusercontent.com/3738898/67052746-132b8980-f10d-11e9-801e-b257cf13716e.png)

Please remove the Java class names from the Reason column:
org.testng.SkipException
java.lang.AssertionError
...

**Comment by keshav-nangare** [comment]
The issue is with teamengine not with ETS so the fix should be added in teamengine. https://github.com/opengeospatial/teamengine/issues/414
